services:
  tsdc_website:
    environment:
      MODE: production
      DATABASE_URL: ${DATABASE_URL}
      TG_USER: ${TG_USER}
      TG_TOKEN: ${TG_TOKEN}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6001:3000"
